version: '3.9'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - INBEV_DATABASE_URL=postgres://db_user:db_pass@db:5432/db_name
      - INBEV_NODE_ENV=production
      - INBEV_JWT_SECRET=${INBEV_JWT_SECRET}
      - INBEV_JWT_EXPIRY=${INBEV_JWT_EXPIRY}
    depends_on:
      - db
    command: npm run start
  db:
    image: postgres
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: db_name
    ports:
      - "5432:5432"
